language: ruby
cache: bundler
bundler_args: --without tools
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - jruby-9.2.7.0
  - truffleruby
matrix:
  allow_failures:
    - rvm: jruby-9.2.7.0
    - rvm: truffleruby
notifications:
  email: false
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
