language: ruby
cache: bundler
bundler_args: --without tools
before_install: gem update --system
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.6
  - jruby-9.2.6.0
  - truffleruby
matrix:
  allow_failures:
    - rvm: truffleruby
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
